apiVersion: v1
kind: ConfigMap
metadata:
  name: core-waap-static-resources
  namespace: backend
data:
  style.css: |
    body { color: green }
  error4xx.html: |
    <html>
    <head>
    <title>Error Page 4xx</title>
    <link rel="stylesheet" type="text/css" href="/style.css"/>
    </head>
    <body>
    <h1>Example Company Error Page</h1>
    <p>example backend status code: %RESPONSE_CODE%</p>
    <p>local logo.jpg resource: <img src="/resources/logo.jpg"></p>
    <p>a remote referenced image: <img src="https://raw.githubusercontent.com/killercoda/scenario-examples/refs/heads/main/assets/logo.png"></p>
    </body>
    </html>
binaryData:
  logo.jpg: |
    /9j/4AAQSkZJRgABAQEASABIAAD/7gAOQWRvYmUAZAAAAAAC/9sAQwAGBAUGBQQGBgUGBwcGCAoQ
    CgoJCQoUDg8MEBcUGBgXFBYWGh0lHxobIxwWFiAsICMmJykqKRkfLTAtKDAlKCko/9sAQwEHBwcK
    CAoTCgoTKBoWGigoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgo
    KCgo/8AAFAgAHQDeBAEiAAIRAQMRAQQiAP/EABwAAQADAQEBAQEAAAAAAAAAAAAFBgcECAMCAf/E
    ADQQAAEDBAEDAwMDAgUFAAAAAAECAwQABQYREiExUQcTQRQiYRUycVKBCCMzQpEWNGLR4f/EABgB
    AQADAQAAAAAAAAAAAAAAAAAEBQYD/8QAKBEAAgIBAwIFBQEAAAAAAAAAAAECEQMEEiExQQUTIlFx
    FDJCgaHB/9oADgQBAAIRAxEEAAA/AMX9KcZxzIBdDklz+jUwhJaQHUt7B3tez3106fmvhGevcHG3
    8cYt7f6TeJaQxOkMlHufcAkpUegB0D+NmrHl06LnUbG7Hj2Orts5w8kOvNBpAQEnYSofuT87/FWC
    4oud/utuwHLHIUBmOymR9TFVtUngNICeXRJ77/irKOJVtj8Wu99mYnLrsm/zc64fqcJNNwUPyil1
    t81/nK9LXqXLi+z9Iz7gUfuPEn+3Sv0tMdyWJanT70ds8mkK3rzsVyQW121UyTKlB1sdCEqKjvfy
    Pg1zNFmMw7c4QccUpRRwWOiNnZ3rv/8AazvJ4rdqft2JXhi3w1wnuUi6RgXFLQvrsjudA9vxVLmt
    tNS30RnvfYStSW3OPHmkHorXxsfFXa8RIOKXbI4j1v8A1yKtP08ae5sBlzW98h0KhvR6/FcmWY1k
    Vpxu0SbxDZagAFDKkBPMc/u05rrs/G/4qNkg3fHT+dvj9l3otTCCgnL7+ltLc2tzaTuV26cW1XYl
    Iay8l6dHW64HE6Qys6AI8VINlRQkrHFRA2N70ajmFuTWIjgd+mWDzW0P9w/jxX0gy4r8uQlhxSnd
    7UDvXTp0qm0pSoxdndSonLnX2MVvLsNS0SW4TymlI/cFhtRSR+d6rNBklxewz0edYubq5l1mQhMU
    hwFUhH0q1O8vI5AFXg0pSlAbDseabHmvLdy9Rsrs/pvezdZsjVxlyEWW6sklxlxuWUqjOHXQlCVK
    QT3HIfHS+3526XSd6ppF+vEFNiU3IhCHI9vifoQspPQ7SVfcR5pSlKA2fY8imx5rz3P/AF2LiXp0
    Yd7ym5S8hW2/KbZuDbb6iYZcKG1rAShPL7tHx3qXnRbz9dgFikXXKbULpLnmWH7i25K0hgrQC6gF
    PHaQQPBNKUpQG29+1NjzWb+ntwuEXOMmxd68v32BbWYz7UqRxU/HW5z5MOLSAFH7QobGwFdd1V4M
    69WfOI8jM7hkaWJ14MWBKgS2XbW8FqKWmFtAc2z/ALSSN8h+6lKUoDcNjzTY81gXpI9kl3Ee8T1Z
    fLZRImKMg3Rj6J323HUpQWP9TR4hPbv17VPemsedkVhsWYXHOrmJk15Dj0Rp1pMIEr0YgaKehH7N
    757G97pSlKA1/dNjzWFyMpu49BLpcBdpAvbd2ciIeDn+ck/qHAN/z7fTXioHMsonRchzsoyHK410
    hT241njw2yuEXFtN+224VILYCnFaIUodD0pSlKA9JbHmmx5FYvzvd8vXqFEuN7ulvctMeBJaRbpA
    bS04YalOIB0doK+pH4FfvG7Zkb/pBasgtGRXiZkDsaNdvamyQtp9SUclx9aGkLBI/B4nfSlKUoDZ
    abHmqH6VXK55RElZbcHH2IN14/ptuUsFMeMnYC1a6e4skqPU6HEfBrKvTO+ZFcmMQl2y65fcrrKm
    gXVuawpVuEX3FhxQcUgJBCQOPBRO+lKUpQHpHY802PNeZ8Qyu7PyMcMK/ZRKySfenY7kSW2Tb3Yy
    H1+5xUtAT9rKd/YoqBHbxYocm65DhmQZpIzW5We4wXpYbhNONpiwfZWtKGnmik81EJBJUdnkNUpS
    lAbtTY81gyPUi8Y1Hlyb0l5yRkFnj3WyRHNnjMWlDbkNO+uvcW2sD4So+K4cvu2TY1Y8zgOX+e9P
    tePW10Sfd6iQt5YdcT432/gAfFKUpQHofYpseayeQLhhuc4tb4mT3S7R7248zIt9ydQ+42hLSliQ
    2oJCkhJSAQdg8vg1W/Rl3I7nYrdfbs7lriXIDr5lybow5DdXxUBpkf5g8jY6EdfypSlAb5seabHm
    vN/prk91lzcJRbL9ks26XCMqRdmLw2RDDAbPJ1pS0JJ04Ua4E7BO6+sPKJGFiM96m33L7bNltr1L
    bkMS7fLVyBKmUoSS30IIBSOhO91uYvOTep9viuY/Ci2x6zOBwyA/oqdKSAlHToNfHbtUHjMrGr3b
    77M9RJ7rl+QShtTq1BSUpT09sJ6E8t9KoVgyS8WBMlFnuD0RMgAOBBH3f89j+a0z6+Ir/D+vlbGC
    8XfYLp/cV89+5vW9/wB6sceXzfVJ20m3fR+3BjNVoHoaxYo7YSnGMXB1OKbuVyd2m+yNpMeHaHXB
    KWt5L41w49k77muiWiXGcjt2ppIjHqdAaJ387/FScmIxJ4l9pKyjqN/FRHtr/wCpv9VWuPLX412r
    jxzKX8ixW2YGYDMVEtYYTPc3x4hXLYTrqvprv81xesz17tkqJjlxvX6jBjtIea/y0oUO4HPXcgDp
    +DX2zLMzcvTWw21NtZjlJRp1C/2lsa2ka6E/PWsweecfcU484txxXdS1Ek/3Nc82Wo7Lt0uenHtR
    M8M8Pc831LgoRUpPbxJuV1vUuqtKqR9JUNMWY9cvcUsoHL2x33rXfxX0sCY7zbkppj2nFKKVfcSP
    PSvzAt/s3aQ8XlKB39pHffnzUulISNJAA8CvnSlKhGnP7VasuB4vY7y5dbRYrfEuC+W3mmgCnl+7
    j8J3861urLSlKUoCCexGwv2B2yPWqK5aXXFPLiqRtBWV8yrXnkSd+a6jYLWV3ZRgslV2ATOOv+4A
    R7eleft6fxUnSlKUoCu3jCMcvNot9ruloiybfASlMVhYPFkJTxATo/CelR7nphhrlqYtq8ehKgsO
    rfbZIVpC1gBSh17kAf8AFXKlKUpQEZj2P2nHIH0Vit0W3xeXItx2wgFX9R13P5PWomJ6fYnDv361
    FsFvauYcLoeS1ris91gdgo+QN1aaUpSlAU63+mWHW+7M3OFj8Jmey77zbyAQpK9k8h179TXQn0+x
    NOQfricetougc973/ZG/c/r125768tb381aaUpSlAVleB4svJP19dht5u/P3fqS0OXP+vXbl/wCW
    t/mu2Ri9lkxrvHkW2M6xdlc5yFp2H1cQnavzpI/4FTNKUpSgIqNj1qjPXB1mCyl24Noalr0SXkoR
    wSFE99JOq6rfbYlutbFuhMIZgsNBltlI+1KANBI/Gq66UpSlAclotsOz22Pb7ZHRGhx0BtppA0lC
    R2Ar8WW0wbJa2LdaYrcWEwCGmWxpKNkk6H8kmu6lKUpQEGMSsQtsO3i2RhDhyvrY7QT0Ze5lfuJ+
    QrkpR2PJ81xXP09xK53v9XuGPW2RceQWp5bIJWodiodlEeSDVppSlKUBG3SxWy6yrfJuMJiS/b3v
    fircTssua1yT4P8A6Hiua64pZLsbgbjbY8g3BluPK5gn3W0EqQlX4BJNTdKUpSgK5jWD4zjLzz1i
    skGE+6ngt1pr71J/p5Hrr8brhs3plhtluDU61Y9BiymgoIcbSQUhSSlWuvyCR/erjSlKUoCETitk
    TGtLAtkb2rSCmEnj/oApKCE/gpOiOxHeo60+m+HWmU7It+N2xp1xPEn2AoBO96SDsJG/gAVbKV//
    2Q==
